// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDAc35N9VNiB5B80UoiABEA4cutXyEK8c',
    appId: '1:717190014755:web:d9b452f072e2cd5a5c4e96',
    messagingSenderId: '717190014755',
    projectId: 'mid-term-4257c',
    authDomain: 'mid-term-4257c.firebaseapp.com',
    storageBucket: 'mid-term-4257c.appspot.com',
    measurementId: 'G-J58TJTEK55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rO_Y4mTY076eWI8UgaK9gFxqQ09xZmo',
    appId: '1:717190014755:android:5dbe3cf8d83a93125c4e96',
    messagingSenderId: '717190014755',
    projectId: 'mid-term-4257c',
    storageBucket: 'mid-term-4257c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbdW2yLgdirp8cuqaH-kKWfCj0YwSfuSo',
    appId: '1:717190014755:ios:3a8dbf55e898d4c25c4e96',
    messagingSenderId: '717190014755',
    projectId: 'mid-term-4257c',
    storageBucket: 'mid-term-4257c.appspot.com',
    iosBundleId: 'com.example.midTerm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbdW2yLgdirp8cuqaH-kKWfCj0YwSfuSo',
    appId: '1:717190014755:ios:3a8dbf55e898d4c25c4e96',
    messagingSenderId: '717190014755',
    projectId: 'mid-term-4257c',
    storageBucket: 'mid-term-4257c.appspot.com',
    iosBundleId: 'com.example.midTerm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDAc35N9VNiB5B80UoiABEA4cutXyEK8c',
    appId: '1:717190014755:web:226777f0f8053cfa5c4e96',
    messagingSenderId: '717190014755',
    projectId: 'mid-term-4257c',
    authDomain: 'mid-term-4257c.firebaseapp.com',
    storageBucket: 'mid-term-4257c.appspot.com',
    measurementId: 'G-W8QHBBMC3V',
  );
}
